# Generated by Django 5.0.6 on 2024-06-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todos",
            old_name="desc",
            new_name="description",
        ),
    ]
